BEGIN TRANSACTION;
CREATE TABLE "pairing" (
	`pairing_index`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`tree_id`	INTEGER NOT NULL,
	`power_id`	INTEGER NOT NULL,
	`faction_id`	INTEGER NOT NULL,
	`tier`	INTEGER NOT NULL,
	`innate`	INTEGER NOT NULL
);
COMMIT;
